// <auto-generated />
using System;
using IA.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IA.MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportContext))]
    partial class MyAirportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IA.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("BagageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("VolID")
                        .HasColumnType("int");

                    b.Property<string>("classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("code_iata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("escale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("prioritaire")
                        .HasColumnType("tinyint");

                    b.Property<string>("ssur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sta")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("BagageID");

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("IA.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("VolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cie")
                        .HasColumnType("int");

                    b.Property<string>("des")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dhc")
                        .HasColumnType("datetime2");

                    b.Property<string>("imm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("jex")
                        .HasColumnType("smallint");

                    b.Property<string>("lig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("pax")
                        .HasColumnType("smallint");

                    b.Property<string>("pkg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VolID");

                    b.ToTable("Vols");
                });
#pragma warning restore 612, 618
        }
    }
}
